import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, test } from "bun:test";

import { generateProjectArtifact, generateProjectArtifactFile, initializePlanningState, writeJsonFile } from "../../src";

const temporaryDirectories: string[] = [];

async function createTempDirectory(): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), "phasekit-project-artifacts-"));
  temporaryDirectories.push(directory);
  return directory;
}

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { force: true, recursive: true })));
});

describe("project markdown artifact generation", () => {
  test("generates deterministic PROJECT.md and PHASES.md from canonical planning json", async () => {
    const rootDir = await createTempDirectory();
    await initializePlanningState(rootDir);
    await writeJsonFile(join(rootDir, ".planning", "project.json"), { stack: "TypeScript + Bun" });
    await writeJsonFile(join(rootDir, ".planning", "requirements.json"), {
      requirements: [
        { id: "REQ-1", text: "One", sources: [{ path: "spec.md", locator: "1" }] },
      ],
    });
    await writeJsonFile(join(rootDir, ".planning", "phases.json"), {
      phases: [
        {
          id: "phase-2",
          source_requirement_ids: ["REQ-1"],
          expected_behavior: "Do thing.",
          relevant_context: ["ctx"],
          likely_change_areas: ["src/a.ts"],
          test_strategy: ["bun test"],
          integration_risks: [],
          done_criteria: ["done"],
          status: "pending",
        },
      ],
    });

    const firstProject = await generateProjectArtifact({ rootDir, artifact: "PROJECT.md" });
    const secondProject = await generateProjectArtifact({ rootDir, artifact: "PROJECT.md" });
    const phases = await generateProjectArtifact({ rootDir, artifact: "PHASES.md" });

    expect(firstProject).toBe(secondProject);
    expect(firstProject).toContain("Stack: TypeScript + Bun");
    expect(firstProject).toContain("Requirements: 1");
    expect(phases).toContain("## phase-2");
    expect(phases).toContain("Source requirement IDs: REQ-1");
  });

  test("writes generated project artifacts through approved writer paths", async () => {
    const rootDir = await createTempDirectory();
    await initializePlanningState(rootDir);

    const result = await generateProjectArtifactFile({ rootDir, artifact: "PROJECT.md" });

    expect(result).toEqual({ path: "PROJECT.md" });
    expect(await readFile(join(rootDir, "PROJECT.md"), "utf8")).toContain("generated by Phasekit");
  });

  test("generates deterministic RUN-SUMMARY.md and VERIFICATION.md from canonical planning json", async () => {
    const rootDir = await createTempDirectory();
    await initializePlanningState(rootDir);
    await writeJsonFile(join(rootDir, ".planning", "runs", "phase-a.json"), {
      id: "phase-a",
      current_phase: "phase-a",
      current_plan: "plan-a",
      current_stage: "execution",
      started_at: "2026-05-19T00:00:00.000Z",
      claimed_tasks: [],
      completed_checks: ["bun test"],
      changed_files: ["src/a.ts"],
      commit_ids: [],
      blockers: [],
    });
    await writeJsonFile(join(rootDir, ".planning", "verifications", "all.json"), {
      id: "verify-all",
      scope: { kind: "all" },
      status: "blocked",
      review_status: "skipped",
      verification_status: "blocked",
      checked_at: "2026-05-19T01:00:00.000Z",
      command_evidence: [],
      output_references: [{ summary: "stored" }],
      findings: [],
      blockers: [{ source: "verification", reason: "Need approval", next_step: "Approve and retry" }],
      linked_requirement_ids: [],
      integration_risks: [],
      missing_check_proposals: [{ id: "missing-check-test", reason: "approval", approval_required: true }],
    });

    const firstRuns = await generateProjectArtifact({ rootDir, artifact: "RUN-SUMMARY.md" });
    const secondRuns = await generateProjectArtifact({ rootDir, artifact: "RUN-SUMMARY.md" });
    const verification = await generateProjectArtifact({ rootDir, artifact: "VERIFICATION.md" });

    expect(firstRuns).toBe(secondRuns);
    expect(firstRuns).toContain("## phase-a");
    expect(firstRuns).toContain("Current stage: execution");
    expect(verification).toContain("## verify-all");
    expect(verification).toContain("Status: blocked");
    expect(verification).toContain("Missing check proposals: 1");
  });
});
