import { validateRulesState } from "../rules/index";
import type { Rule, RulesState } from "../state/schema";

export const agentsMdManagedMarker = "<!-- phasekit:managed agents-md v1 -->";

export type AgentsMdProjectContext = {
  projectName: string;
  stack?: string;
  packageManager?: string;
  languages?: string[];
  frameworks?: string[];
  architectureBoundaries?: string[];
  verificationCommands?: string[];
  commandNames?: string[];
  toolNames?: string[];
  globalPreferences?: string[];
};

export type GenerateAgentsMdOptions = {
  rulesState: RulesState;
  projectContext: AgentsMdProjectContext;
};

/** Generates deterministic managed AGENTS.md content from canonical rules and explicit context. */
export function generateAgentsMd(options: GenerateAgentsMdOptions): string {
  const rulesState = validateRulesState(options.rulesState);
  const context = normalizeProjectContext(options.projectContext);
  const rules = [...rulesState.rules].sort(compareRules);

  return [
    agentsMdManagedMarker,
    "# AGENTS.md",
    "",
    "This file is generated by Phasekit. Do not edit it manually.",
    "Edit `.planning/rules.json` or the explicit project context used by the generator, then regenerate this file.",
    "Markdown artifacts are not canonical state and are never proof of completion.",
    "",
    "## Project Context",
    "",
    `- Project: ${context.projectName}`,
    `- Stack: ${context.stack ?? "Not specified by project context."}`,
    `- Package manager: ${context.packageManager ?? "Not specified by project context."}`,
    `- Languages: ${formatInlineList(context.languages)}`,
    `- Frameworks: ${formatInlineList(context.frameworks)}`,
    "",
    "## Strict Agent Instructions",
    "",
    "- Do not make assumptions when an answer affects architecture, public behavior, state schema, plugin behavior, command names, persistence, dependencies, security, or implementation scope.",
    "- Make the smallest correct change; do not perform broad rewrites, unrelated refactors, or scope expansion.",
    "- Keep canonical state in committed `.planning` JSON files; do not treat markdown, chat history, summaries, generated artifacts, or caches as runtime state.",
    "- Run review and verification before commit when the active plan or project policy requires it; do not claim completion from file existence alone.",
    "- Keep durable planning memory and TODO state current through the approved Phasekit state/update flow when the active role is responsible for it.",
    "- Protect user work: do not overwrite unmanaged files, secrets, credentials, or unrelated local changes.",
    "- Respect project boundaries and package ownership; do not import across adapter or installer boundaries unless the approved architecture allows it.",
    "",
    "## Baseline Expectations",
    "",
    "- Coding conventions: follow existing project patterns and prefer clear, maintainable code over clever abstractions.",
    "- Tests: run the narrowest checks that prove the change, then broader checks when required by the plan.",
    "- Architecture boundaries: follow the explicit boundaries below and stop if a requested change needs a new public boundary decision.",
    "- Dependencies: prefer the standard library and existing dependencies; add packages only with a clear approved need.",
    "- Commits: commit only when the active workflow explicitly requires or approves it, and only after required checks pass.",
    "- Documentation: update nearby docs or generated artifacts only when behavior or instructions change and the plan includes that scope.",
    "- Security: do not expose secrets, run unapproved commands, or weaken safety checks for convenience.",
    "- User preferences: apply explicit preferences from canonical rules and project context, not inferred preferences from generated markdown.",
    "",
    "## Architecture Boundaries",
    "",
    ...formatBulletList(context.architectureBoundaries),
    "",
    "## Canonical Project Rules",
    "",
    ...formatRules(rules),
    "",
    "## Approved Commands And Tools",
    "",
    "Commands:",
    ...formatBulletList(context.commandNames),
    "",
    "Tools:",
    ...formatBulletList(context.toolNames),
    "",
    "Verification commands:",
    ...formatBulletList(context.verificationCommands),
    "",
    "## Explicit User Preferences",
    "",
    ...formatBulletList(context.globalPreferences),
    "",
  ].join("\n");
}

/** Returns true when existing AGENTS.md content is managed by this generator. */
export function isManagedAgentsMdContent(content: string): boolean {
  return content.startsWith(agentsMdManagedMarker);
}

/** Enforces the managed-marker overwrite policy without performing file IO. */
export function assertCanOverwriteAgentsMd(existingContent: string | null): void {
  if (existingContent !== null && !isManagedAgentsMdContent(existingContent)) {
    throw new Error("Refusing to overwrite unmanaged AGENTS.md content.");
  }
}

type NormalizedProjectContext = Required<Pick<AgentsMdProjectContext, "projectName">> & {
  stack?: string;
  packageManager?: string;
  languages: string[];
  frameworks: string[];
  architectureBoundaries: string[];
  verificationCommands: string[];
  commandNames: string[];
  toolNames: string[];
  globalPreferences: string[];
};

function normalizeProjectContext(context: AgentsMdProjectContext): NormalizedProjectContext {
  const projectName = normalizeRequiredText(context.projectName, "projectName");

  return {
    projectName,
    stack: normalizeOptionalText(context.stack),
    packageManager: normalizeOptionalText(context.packageManager),
    languages: normalizeTextList(context.languages),
    frameworks: normalizeTextList(context.frameworks),
    architectureBoundaries: normalizeTextList(context.architectureBoundaries),
    verificationCommands: normalizeTextList(context.verificationCommands),
    commandNames: normalizeTextList(context.commandNames),
    toolNames: normalizeTextList(context.toolNames),
    globalPreferences: normalizeTextList(context.globalPreferences),
  };
}

function normalizeRequiredText(value: string, fieldName: string): string {
  const normalized = value.trim();

  if (normalized.length === 0) {
    throw new Error(`Cannot generate AGENTS.md: project context ${fieldName} is required.`);
  }

  return assertSafeMarkdownText(normalized, `project context ${fieldName}`);
}

function normalizeOptionalText(value: string | undefined): string | undefined {
  const normalized = value?.trim();

  return normalized && normalized.length > 0
    ? assertSafeMarkdownText(normalized, "project context value")
    : undefined;
}

function normalizeTextList(values: string[] | undefined): string[] {
  return [...new Set(values?.map((value) => value.trim()).filter((value) => value.length > 0) ?? [])]
    .map((value) => assertSafeMarkdownText(value, "project context list item"))
    .sort(compareText);
}

function assertSafeMarkdownText(value: string, fieldName: string): string {
  if (/[\r\n]/.test(value)) {
    throw new Error(`Cannot generate AGENTS.md: ${fieldName} must be a single line.`);
  }

  if (/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(value)) {
    throw new Error(`Cannot generate AGENTS.md: ${fieldName} contains unsupported control characters.`);
  }

  return value;
}

function compareRules(left: Rule, right: Rule): number {
  return compareText(left.category, right.category)
    || compareText(left.id, right.id)
    || compareText(left.text, right.text);
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function formatInlineList(values: string[]): string {
  return values.length > 0 ? values.join(", ") : "Not specified by project context.";
}

function formatBulletList(values: string[]): string[] {
  if (values.length === 0) {
    return ["- Not specified by project context."];
  }

  return values.map((value) => `- ${value}`);
}

function formatRules(rules: Rule[]): string[] {
  if (rules.length === 0) {
    return ["- No canonical project rules are defined in `.planning/rules.json`."];
  }

  const lines: string[] = [];
  let currentCategory = "";

  for (const rule of rules) {
    const ruleId = assertSafeMarkdownText(rule.id, "rule id");
    const ruleCategory = assertSafeMarkdownText(rule.category, `rule ${ruleId} category`);
    const ruleText = assertSafeMarkdownText(rule.text, `rule ${ruleId} text`);

    if (ruleCategory !== currentCategory) {
      if (lines.length > 0) {
        lines.push("");
      }

      currentCategory = ruleCategory;
      lines.push(`### ${ruleCategory}`);
      lines.push("");
    }

    lines.push(`- \`${ruleId}\`: ${ruleText}`);
  }

  return lines;
}
