import { readdir } from "node:fs/promises";
import { join } from "node:path";
import type { ZodType } from "zod";

import { readJsonFile } from "../state/json";
import {
  phasesStateSchema,
  projectStateSchema,
  requirementsStateSchema,
  runStateSchema,
} from "../state/schema";
import { verificationResultSchema } from "../verify/schemas";
import { projectArtifactManagedMarker, writeGeneratedArtifact, type WriteGeneratedArtifactResult } from "./write";

const managedArtifacts = ["PROJECT.md", "PHASES.md", "RUN-SUMMARY.md", "VERIFICATION.md"] as const;

export type SupportedProjectArtifact = typeof managedArtifacts[number];

export async function generateProjectArtifact(options: {
  rootDir?: string;
  artifact: SupportedProjectArtifact;
}): Promise<string> {
  const rootDir = options.rootDir ?? process.cwd();

  switch (options.artifact) {
    case "PROJECT.md":
      return generateProjectMd(rootDir);
    case "PHASES.md":
      return generatePhasesMd(rootDir);
    case "RUN-SUMMARY.md":
      return generateRunSummaryMd(rootDir);
    case "VERIFICATION.md":
      return generateVerificationMd(rootDir);
  }
}

export async function generateProjectArtifactFile(options: {
  rootDir?: string;
  artifact: SupportedProjectArtifact;
}): Promise<WriteGeneratedArtifactResult> {
  const rootDir = options.rootDir ?? process.cwd();
  const content = await generateProjectArtifact({ rootDir, artifact: options.artifact });

  return writeGeneratedArtifact({
    rootDir,
    path: options.artifact,
    content,
  });
}

async function generateProjectMd(rootDir: string): Promise<string> {
  const planningDir = join(rootDir, ".planning");
  const [project, requirements, phases] = await Promise.all([
    readJsonFile(join(planningDir, "project.json"), projectStateSchema),
    readJsonFile(join(planningDir, "requirements.json"), requirementsStateSchema),
    readJsonFile(join(planningDir, "phases.json"), phasesStateSchema),
  ]);

  const statusCounts = countBy(phases.phases.map((phase) => phase.status));

  return [
    projectArtifactManagedMarker,
    "# PROJECT.md",
    "",
    "This file is generated by Phasekit from canonical `.planning/*.json` state.",
    "Markdown artifacts are not canonical state and are never proof of completion.",
    "",
    "## Project",
    "",
    `- Stack: ${project.stack ?? "not set"}`,
    "",
    "## Current Planning Totals",
    "",
    `- Requirements: ${requirements.requirements.length}`,
    `- Phases: ${phases.phases.length}`,
    `- Pending phases: ${statusCounts.pending ?? 0}`,
    `- In progress phases: ${statusCounts.in_progress ?? 0}`,
    `- Blocked phases: ${statusCounts.blocked ?? 0}`,
    `- Complete phases: ${statusCounts.complete ?? 0}`,
    "",
  ].join("\n");
}

async function generatePhasesMd(rootDir: string): Promise<string> {
  const phases = await readJsonFile(join(rootDir, ".planning", "phases.json"), phasesStateSchema);
  const sortedPhases = [...phases.phases].sort((left, right) => compareText(left.id, right.id));

  const lines = [
    projectArtifactManagedMarker,
    "# PHASES.md",
    "",
    "This file is generated by Phasekit from canonical `.planning/phases.json` state.",
    "Markdown artifacts are not canonical state and are never proof of completion.",
    "",
  ];

  if (sortedPhases.length === 0) {
    lines.push("No phases are currently defined.", "");
    return lines.join("\n");
  }

  for (const phase of sortedPhases) {
    lines.push(`## ${phase.id}`);
    lines.push("");
    lines.push(`- Status: ${phase.status}`);
    lines.push(`- Source requirement IDs: ${phase.source_requirement_ids.slice().sort(compareText).join(", ")}`);
    lines.push(`- Expected behavior: ${phase.expected_behavior}`);
    lines.push(`- Relevant context count: ${phase.relevant_context.length}`);
    lines.push(`- Likely change areas count: ${phase.likely_change_areas.length}`);
    lines.push(`- Test strategy count: ${phase.test_strategy.length}`);
    lines.push(`- Integration risks count: ${phase.integration_risks.length}`);
    lines.push(`- Done criteria count: ${phase.done_criteria.length}`);
    lines.push("");
  }

  return lines.join("\n");
}

async function generateRunSummaryMd(rootDir: string): Promise<string> {
  const runs = await readTypedJsonCollection(join(rootDir, ".planning", "runs"), runStateSchema);
  const sortedRuns = runs.sort((left, right) => compareText(left.id, right.id));
  const lines = [
    projectArtifactManagedMarker,
    "# RUN-SUMMARY.md",
    "",
    "This file is generated by Phasekit from canonical `.planning/runs/*.json` state.",
    "Markdown artifacts are not canonical state and are never proof of completion.",
    "",
  ];

  if (sortedRuns.length === 0) {
    lines.push("No runs are currently recorded.", "");
    return lines.join("\n");
  }

  for (const run of sortedRuns) {
    lines.push(`## ${run.id}`);
    lines.push("");
    lines.push(`- Phase: ${run.current_phase}`);
    lines.push(`- Current stage: ${run.current_stage}`);
    lines.push(`- Current plan: ${run.current_plan ?? "none"}`);
    lines.push(`- Started at: ${run.started_at}`);
    lines.push(`- Claimed tasks: ${run.claimed_tasks.length}`);
    lines.push(`- Completed checks: ${run.completed_checks.length}`);
    lines.push(`- Changed files: ${run.changed_files.length}`);
    lines.push(`- Blockers: ${run.blockers.length}`);
    lines.push("");
  }

  return lines.join("\n");
}

async function generateVerificationMd(rootDir: string): Promise<string> {
  const results = await readTypedJsonCollection(join(rootDir, ".planning", "verifications"), verificationResultSchema);
  const sortedResults = results.sort((left, right) => compareText(left.id, right.id));
  const lines = [
    projectArtifactManagedMarker,
    "# VERIFICATION.md",
    "",
    "This file is generated by Phasekit from canonical `.planning/verifications/*.json` state.",
    "Markdown artifacts are not canonical state and are never proof of completion.",
    "",
  ];

  if (sortedResults.length === 0) {
    lines.push("No verification results are currently recorded.", "");
    return lines.join("\n");
  }

  for (const result of sortedResults) {
    lines.push(`## ${result.id}`);
    lines.push("");
    lines.push(`- Scope kind: ${result.scope.kind}`);
    lines.push(`- Status: ${result.status}`);
    lines.push(`- Review status: ${result.review_status}`);
    lines.push(`- Verification status: ${result.verification_status}`);
    lines.push(`- Checked at: ${result.checked_at}`);
    lines.push(`- Linked requirement IDs: ${result.linked_requirement_ids.length}`);
    lines.push(`- Findings: ${result.findings.length}`);
    lines.push(`- Blockers: ${result.blockers.length}`);
    lines.push(`- Missing check proposals: ${result.missing_check_proposals.length}`);
    lines.push("");
  }

  return lines.join("\n");
}

async function readTypedJsonCollection<T>(directory: string, schema: ZodType<T>): Promise<T[]> {
  let entries: string[];

  try {
    entries = await readdir(directory);
  } catch (error) {
    if (isNotFoundError(error)) {
      return [];
    }

    throw error;
  }

  const fileNames = entries.filter((name) => name.endsWith(".json")).sort(compareText);
  return Promise.all(fileNames.map((fileName) => readJsonFile(join(directory, fileName), schema)));
}

function countBy(values: string[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const value of values) {
    counts[value] = (counts[value] ?? 0) + 1;
  }
  return counts;
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function isNotFoundError(error: unknown): boolean {
  return Boolean(error && typeof error === "object" && "code" in error && error.code === "ENOENT");
}
